const canvas=document.getElementById('game'),ctx=canvas.getContext('2d');
const SAVE='tower-phase3-save-v1';
const $=id=>document.getElementById(id);
const ui={coins:$('coins'),wave:$('wave'),enemies:$('enemies'),best:$('best-wave'),hp:$('tower-hp'),lvl:$('tower-level'),fill:$('tower-health-fill'),state:$('wave-state'),progress:$('wave-progress'),msg:$('combat-message'),shards:$('shards'),runs:$('runs'),kills:$('kills'),earned:$('earned'),highest:$('lifetime-wave'),ability:$('ability'),abilityTimer:$('ability-timer'),sound:$('sound-toggle'),achievements:$('achievements')};
const perm={shards:0,levels:{power:0,income:0,vitality:0,starting:0},lifetime:{runs:0,kills:0,earned:0,highestWave:0,bosses:0,criticals:0},achievements:{}};
const meta={power:{base:3,g:2.15,desc:l=>`+${l*2}% damage`},income:{base:5,g:1.9,desc:l=>`+${l*5}% enemy coins`},vitality:{base:6,g:1.95,desc:l=>`+${l*4}% max health`},starting:{base:8,g:2,desc:l=>`+${l*15} starting coins`}};
const run={damage:0,speed:0,range:0,health:0,crit:0,multi:0};
const state={coins:0,wave:1,best:0,spawned:0,defeated:0,enemies:[],bullets:[],particles:[],texts:[],spawn:0,shot:0,delay:0,overdrive:0,gameOver:false,last:performance.now()};
state.tower={damage:10,speed:1,range:210,maxHealth:100,health:100,level:1,crit:0.05,multi:1};
const achievements=[['wave10','First Milestone','Reach wave 10',()=>state.best>=10],['wave25','Veteran','Reach wave 25',()=>state.best>=25],['boss','Boss Hunter','Defeat a boss',()=>perm.lifetime.bosses>=1],['kills100','Centurion','Defeat 100 enemies',()=>perm.lifetime.kills>=100],['crit','Lucky Shot','Land 25 critical hits',()=>perm.lifetime.criticals>=25],['speed','Overclocked','Reach 3.0 attacks/sec',()=>state.tower.speed>=3]];
function load(){try{const s=JSON.parse(localStorage.getItem(SAVE)||localStorage.getItem('tower-phase2-save-v1')||'null');if(s?.permanent)Object.assign(perm,s.permanent);if(s?.lastSeen){const h=Math.min(12,Math.max(0,(Date.now()-s.lastSeen)/36e5));if(h>.02){state.coins=Math.floor(h*(18+perm.levels.income*3))+perm.levels.starting*15;showModal(`You were away for ${h.toFixed(1)} hours. ${state.coins.toLocaleString()} coins are ready.`)}}}catch{}state.tower.maxHealth=Math.round(100*(1+perm.levels.vitality*.04));state.tower.health=state.tower.maxHealth;state.coins+=perm.levels.starting*15;}
function save(){try{localStorage.setItem(SAVE,JSON.stringify({permanent:perm,lastSeen:Date.now()}))}catch{}}
function showModal(text){const m=$('offline-modal');if(m){$('offline-copy').textContent=text;m.classList.remove('hidden')}}
function resize(){const r=canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);canvas.width=r.width*d;canvas.height=r.height*d;ctx.setTransform(d,0,0,d,0,0)}addEventListener('resize',resize);resize();
function pos(){return{x:canvas.clientWidth/2,y:canvas.clientHeight/2}} function cost(t){return Math.floor(([25,30,35,40,55,90][['damage','speed','range','health','crit','multi'].indexOf(t)]||25)*Math.pow(1.5,run[t]))}function mcost(t){const c=meta[t];return Math.floor(c.base*Math.pow(c.g,perm.levels[t]))}function waveSize(){return 5+state.wave*2+(state.wave%10===0?1:0)}
function enemy(){const p=pos(),a=Math.random()*Math.PI*2,r=Math.max(canvas.clientWidth,canvas.clientHeight)*.58+30,boss=state.wave%10===0&&state.spawned===waveSize()-1,type=boss?'boss':Math.random()<.16?'tank':Math.random()<.18?'swift':'normal';let hp=(24+state.wave*8)*Math.pow(1.045,state.wave-1),speed=25+state.wave*1.8+Math.random()*9,reward=7+Math.floor(state.wave*1.5),rad=9;if(type==='tank'){hp*=3;speed*=.55;rad=15;reward*=2}if(type==='swift'){hp*=.55;speed*=1.8;rad=7;reward*=1.3}if(boss){hp*=18;speed*=.45;rad=27;reward*=15}hp=Math.floor(hp);return{x:p.x+Math.cos(a)*r,y:p.y+Math.sin(a)*r,hp,maxHp:hp,speed,radius:rad,reward:Math.floor(reward*(1+perm.levels.income*.05)),type,wobble:Math.random()*7}}
function burst(x,y,n,c){for(let i=0;i<n;i++){const a=Math.random()*6.28,s=20+Math.random()*110;state.particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:.3+Math.random()*.5,max:.8,size:1+Math.random()*3,c})}}function text(t,x,y,c){state.texts.push({t,x,y,c,life:.8})}function msg(t){ui.msg.textContent=t}
function target(){const p=pos();return state.enemies.filter(e=>Math.hypot(e.x-p.x,e.y-p.y)<=state.tower.range).sort((a,b)=>Math.hypot(a.x-p.x,a.y-p.y)-Math.hypot(b.x-p.x,b.y-p.y))[0]}
function kill(e){const i=state.enemies.indexOf(e);if(i<0)return;state.enemies.splice(i,1);let reward=e.reward;if(e.type==='boss')perm.lifetime.bosses++;state.coins+=reward;perm.lifetime.kills++;perm.lifetime.earned+=reward;state.defeated++;burst(e.x,e.y,e.type==='boss'?40:12,e.type==='boss'?'#f4c95d':'#69e0c0');text(`+${reward}`,e.x,e.y-16,'#f4c95d');msg(e.type==='boss'?'BOSS DESTROYED!':`Enemy destroyed +${reward}`);checkAchievements()}
function hit(e){const d=7+Math.floor(state.wave*1.3)*(e.type==='boss'?2:1);state.tower.health-=d;burst(e.x,e.y,10,'#ff6d7d');text(`-${d}`,pos().x,pos().y-42,'#ff6d7d');if(state.tower.health<=0){state.tower.health=0;state.gameOver=true;perm.lifetime.highestWave=Math.max(perm.lifetime.highestWave,state.wave);save();msg('TOWER FALLEN')}}
function fire(e){const p=pos();let dmg=state.tower.damage*(1+perm.levels.power*.02)*(state.overdrive>0?2:1);const crit=Math.random()<state.tower.crit;if(crit){dmg*=2;perm.lifetime.criticals++;text('CRIT!',e.x,e.y-25,'#f4c95d')}state.bullets.push({x:p.x,y:p.y,target:e,speed:680,damage:dmg,life:1.4});for(let i=1;i<state.tower.multi;i++)state.bullets.push({x:p.x,y:p.y,target:e,speed:640,damage:dmg*.7,life:1.4});}
function nextWave(){state.wave++;state.best=Math.max(state.best,state.wave);state.spawned=0;state.defeated=0;state.spawn=0;state.delay=0;state.tower.health=Math.min(state.tower.maxHealth,state.tower.health+state.tower.maxHealth*.1);msg(state.wave%10===0?'BOSS WAVE INCOMING':'Wave '+state.wave+' incoming');burst(pos().x,pos().y,20,state.wave%10===0?'#f4c95d':'#7da7ff');checkAchievements()}
function update(dt){if(state.gameOver)return;state.overdrive=Math.max(0,state.overdrive-dt);if(state.spawned<waveSize()){state.spawn-=dt;if(state.spawn<=0){state.enemies.push(enemy());state.spawned++;state.spawn=Math.max(.18,.65-state.wave*.01)}}else if(!state.enemies.length){state.delay+=dt;if(state.delay>1.5)nextWave()}state.shot-=dt;if(state.shot<=0){const t=target();if(t){fire(t);state.shot=1/state.tower.speed}else state.shot=.05}const p=pos();for(const e of [...state.enemies]){const dx=p.x-e.x,dy=p.y-e.y,d=Math.hypot(dx,dy);e.wobble+=dt*3;if(d<40){hit(e);state.enemies=state.enemies.filter(x=>x!==e);continue}e.x+=dx/d*e.speed*dt;e.y+=dy/d*e.speed*dt}for(const b of [...state.bullets]){b.life-=dt;if(!state.enemies.includes(b.target)){state.bullets=state.bullets.filter(x=>x!==b);continue}const dx=b.target.x-b.x,dy=b.target.y-b.y,d=Math.hypot(dx,dy);if(d<9||b.life<=0){if(b.life>0){b.target.hp-=b.damage;if(b.target.hp<=0)kill(b.target);else burst(b.target.x,b.target.y,3,'#d9fff5')}state.bullets=state.bullets.filter(x=>x!==b)}else{b.x+=dx/d*b.speed*dt;b.y+=dy/d*b.speed*dt}}for(const q of [...state.particles]){q.life-=dt;q.x+=q.vx*dt;q.y+=q.vy*dt;q.vx*=.97;q.vy*=.97;if(q.life<=0)state.particles.splice(state.particles.indexOf(q),1)}for(const q of [...state.texts]){q.life-=dt;q.y-=22*dt;if(q.life<=0)state.texts.splice(state.texts.indexOf(q),1)}}
function draw(){const w=canvas.clientWidth,h=canvas.clientHeight;ctx.fillStyle='#09111f';ctx.fillRect(0,0,w,h);ctx.strokeStyle='rgba(88,116,150,.12)';for(let x=0;x<w;x+=36){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke()}for(let y=0;y<h;y+=36){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()}const p=pos();ctx.beginPath();ctx.arc(p.x,p.y,state.tower.range,0,6.28);ctx.fillStyle='rgba(105,224,192,.025)';ctx.fill();ctx.strokeStyle='rgba(105,224,192,.1)';ctx.setLineDash([4,8]);ctx.stroke();ctx.setLineDash([]);for(const b of state.bullets){ctx.beginPath();ctx.arc(b.x,b.y,3,0,6.28);ctx.fillStyle='#d9fff5';ctx.shadowColor='#69e0c0';ctx.shadowBlur=12;ctx.fill();ctx.shadowBlur=0}for(const e of state.enemies){const boss=e.type==='boss';ctx.save();ctx.translate(e.x,e.y+Math.sin(e.wobble)*1.2);ctx.shadowBlur=boss?28:12;ctx.shadowColor=boss?'rgba(244,201,93,.45)':'rgba(105,224,192,.2)';ctx.beginPath();ctx.arc(0,0,e.radius,0,6.28);ctx.fillStyle=boss?'#765b20':e.type==='tank'?'#4b466e':e.type==='swift'?'#31548f':'#2c7568';ctx.fill();ctx.strokeStyle=boss?'#f4c95d':e.type==='tank'?'#a78cff':e.type==='swift'?'#7da7ff':'#69e0c0';ctx.lineWidth=boss?3:1.5;ctx.stroke();ctx.restore();const bw=e.radius*2.6;ctx.fillStyle='#202a39';ctx.fillRect(e.x-bw/2,e.y-e.radius-8,bw,4);ctx.fillStyle='#ff7180';ctx.fillRect(e.x-bw/2,e.y-e.radius-8,bw*Math.max(0,e.hp/e.maxHp),4)}ctx.save();ctx.shadowColor='rgba(105,224,192,.3)';ctx.shadowBlur=state.overdrive>0?45:28;ctx.beginPath();ctx.arc(p.x,p.y,34,0,6.28);ctx.fillStyle='#12283a';ctx.fill();ctx.restore();ctx.beginPath();ctx.arc(p.x,p.y,28,0,6.28);ctx.fillStyle='#172f42';ctx.fill();ctx.strokeStyle=state.overdrive>0?'#f4c95d':'#69e0c0';ctx.lineWidth=2;ctx.stroke();ctx.beginPath();ctx.arc(p.x,p.y,10,0,6.28);ctx.fillStyle=state.overdrive>0?'#f4c95d':'#69e0c0';ctx.fill();for(const q of state.particles){ctx.globalAlpha=Math.max(0,q.life/q.max);ctx.fillStyle=q.c;ctx.fillRect(q.x,q.y,q.size,q.size)}ctx.globalAlpha=1;for(const q of state.texts){ctx.globalAlpha=Math.max(0,q.life/.8);ctx.fillStyle=q.c;ctx.font='800 11px system-ui';ctx.textAlign='center';ctx.fillText(q.t,q.x,q.y)}ctx.globalAlpha=1;if(state.gameOver){ctx.fillStyle='rgba(5,9,16,.75)';ctx.fillRect(0,0,w,h);ctx.textAlign='center';ctx.fillStyle='#ff7b88';ctx.font='900 28px system-ui';ctx.fillText('TOWER FALLEN',w/2,h/2-20);ctx.fillStyle='#b5c1d1';ctx.font='600 12px system-ui';ctx.fillText(`Wave ${state.wave} reached`,w/2,h/2+10)}}
function buyRun(t){const c=cost(t);if(state.gameOver||state.coins<c)return;state.coins-=c;run[t]++;if(t==='damage')state.tower.damage+=2;if(t==='speed')state.tower.speed+=.1;if(t==='range')state.tower.range+=15;if(t==='health'){state.tower.maxHealth+=20;state.tower.health+=20}if(t==='crit')state.tower.crit+=.02;if(t==='multi')state.tower.multi++;state.tower.level++;msg('Upgrade purchased');checkAchievements()}
function buyMeta(t){const c=mcost(t);if(perm.shards<c)return;perm.shards-=c;perm.levels[t]++;state.tower.maxHealth=Math.round(100*(1+perm.levels.vitality*.04));state.tower.health=Math.min(state.tower.maxHealth,state.tower.health+20);msg('Research complete');save()}
function restart(){perm.lifetime.runs++;perm.lifetime.highestWave=Math.max(perm.lifetime.highestWave,state.wave);perm.shards+=Math.floor(Math.max(0,state.best-4)/3);state.coins=perm.levels.starting*15;state.wave=1;state.best=0;state.spawned=0;state.defeated=0;state.enemies=[];state.bullets=[];state.particles=[];state.texts=[];state.gameOver=false;state.tower={damage:10,speed:1,range:210,maxHealth:Math.round(100*(1+perm.levels.vitality*.04)),health:Math.round(100*(1+perm.levels.vitality*.04)),level:1,crit:.05,multi:1};Object.keys(run).forEach(k=>run[k]=0);msg('New run started');save()}
function checkAchievements(){for(const a of achievements){if(!perm.achievements[a[0]]&&a[3]()){perm.achievements[a[0]]=Date.now();msg('Achievement unlocked: '+a[1]);burst(pos().x,pos().y,25,'#f4c95d');}}ui.achievements.textContent=Object.keys(perm.achievements).length+'/'+achievements.length}
function activate(){if(state.overdrive>0||state.gameOver)return;state.overdrive=10;msg('OVERDRIVE ACTIVE — 2× DAMAGE');burst(pos().x,pos().y,35,'#f4c95d');tone(520,.18)}
function tone(f,d){if(ui.sound.checked===false)return;try{const a=new AudioContext(),o=a.createOscillator(),g=a.createGain();o.frequency.value=f;o.connect(g);g.connect(a.destination);g.gain.value=.04;o.start();o.stop(a.currentTime+d)}catch{}}
function uiUpdate(){ui.coins.textContent=Math.floor(state.coins).toLocaleString();ui.wave.textContent=state.wave;ui.enemies.textContent=state.enemies.length;ui.best.textContent=state.best;ui.hp.textContent=`${Math.ceil(state.tower.health)} / ${state.tower.maxHealth}`;ui.lvl.textContent='LV '+state.tower.level;ui.fill.style.width=Math.max(0,state.tower.health/state.tower.maxHealth*100)+'%';ui.state.textContent=state.wave%10===0?'BOSS WAVE':state.gameOver?'GAME OVER':'WAVE '+state.wave;ui.progress.textContent=state.defeated+' / '+waveSize()+' defeated';ui.shards.textContent=perm.shards.toLocaleString();ui.runs.textContent=perm.lifetime.runs.toLocaleString();ui.kills.textContent=perm.lifetime.kills.toLocaleString();ui.earned.textContent=perm.lifetime.earned.toLocaleString();ui.highest.textContent=perm.lifetime.highestWave;for(const t of ['damage','speed','range','health','crit','multi']){const b=document.querySelector(`[data-upgrade="${t}"]`);if(!b)continue;b.querySelector('.cost-value').textContent=cost(t);b.querySelector('.upgrade-value').textContent=t==='speed'?state.tower.speed.toFixed(1)+' /s':t==='crit'?Math.round(state.tower.crit*100)+'% crit':t==='multi'?state.tower.multi+' projectiles':t==='damage'?state.tower.damage:t==='range'?state.tower.range:state.tower.maxHealth;b.disabled=state.gameOver||state.coins<cost(t)}for(const t of Object.keys(meta)){const b=document.querySelector(`[data-meta="${t}"]`);b.querySelector('.cost-value').textContent=mcost(t);b.querySelector('.upgrade-value').textContent=meta[t].desc(perm.levels[t]+1);b.querySelector('.level').textContent='LV '+perm.levels[t];b.disabled=perm.shards<mcost(t)}ui.ability.disabled=state.overdrive>0||state.gameOver;ui.abilityTimer.textContent=state.overdrive>0?Math.ceil(state.overdrive)+'s':'READY';checkAchievements()}
$('reset').onclick=restart;ui.ability.onclick=activate;for(const b of document.querySelectorAll('[data-upgrade]'))b.onclick=()=>buyRun(b.dataset.upgrade);for(const b of document.querySelectorAll('[data-meta]'))b.onclick=()=>buyMeta(b.dataset.meta);$('offline-close').onclick=()=>$('offline-modal').classList.add('hidden');
load();uiUpdate();setInterval(()=>{save();uiUpdate()},5000);addEventListener('beforeunload',save);function loop(t){const dt=Math.min(.05,(t-state.last)/1000);state.last=t;update(dt);draw();uiUpdate();requestAnimationFrame(loop)}requestAnimationFrame(loop);